POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "react",
  "description": "react is most popular web framework",
  "duration": 2000
}

###

GET http://localhost:3333/videos?search=react
Content-Type: application/json

###

PUT http://localhost:3333/videos/342822b5-bb0f-4234-950a-320313082b2f
Content-Type: application/json

{
  "title": "Vídeo 2 - UPDATED"
}

###

DELETE http://localhost:3333/videos/d3985c44-de21-4e73-b171-9690e17329c8
Content-Type: application/json